version: "3.8"

services:
  ml-backend:
    container_name: label-studio-ml-backend-yolov8-jewelry
    image: humansignal/ml-backend:v0
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    build: .
    environment:
      - MODEL_DIR=/data/models
      - WORKERS=2
      - THREADS=4

    ports:
      - 11302:9090
